// src/pages/admin/roles/component/RoleForm.jsx
import React, { useEffect, useState } from 'react';
import Input from '@/components/Input';
import Textarea from '@/components/Textarea';
import SelectPrivilegeInput from './SelectPrivilegeInput';

const RoleForm = ({ 
  role = {}, 
  privileges = [], 
  selectedPrivileges = [],
  onFormChange 
}) => {
  const [formData, setFormData] = useState({
    roleName: role?.roleName || '',
    roleDescription: role?.roleDescription || '',
    privileges: selectedPrivileges || [],
  });

  useEffect(() => {
    if (role?.roleUuid) {
      setFormData({
        roleName: role?.roleName || '',
        roleDescription: role?.roleDescription || '',
        privileges: selectedPrivileges || [],
      });
    }
  }, [role?.roleUuid, selectedPrivileges]);

  const handleInputChange = (e) => {
    const { name, value } = e.target;
    const updated = {
      ...formData,
      [name]: value,
    };
    setFormData(updated);
    if (onFormChange) {
      onFormChange(updated);
    }
  };

  const handlePrivilegesChange = (selectedPrivs) => {
    const updated = {
      ...formData,
      privileges: selectedPrivs,
    };
    setFormData(updated);
    if (onFormChange) {
      onFormChange(updated);
    }
  };

  return (
    <div className="space-y-8">
      <div className="grid grid-cols-1 sm:grid-cols-2 gap-6">
        <div className="bg-gray-50 rounded-lg p-6 border border-gray-200">
          <Input
            name="roleName"
            label="Role Name"
            value={formData.roleName}
            onChange={handleInputChange}
            placeholder="e.g., Administrator, Editor"
            required
          />
        </div>

        <div className="bg-gray-50 rounded-lg p-6 border border-gray-200">
          <Textarea
            name="roleDescription"
            label="Role Description"
            value={formData.roleDescription}
            onChange={handleInputChange}
            placeholder="Describe the purpose of this role..."
            rows={4}
            required
          />
        </div>
      </div>

      <div className="bg-gray-50 rounded-lg p-6 border border-gray-200">
        <SelectPrivilegeInput
          label="Assign Privileges"
          name="privileges"
          options={privileges}
          selectedPrivileges={formData.privileges}
          onChange={handlePrivilegesChange}
          required
        />
      </div>
    </div>
  );
};

export default RoleForm;

// src/features/admin/role/form/RoleForm.vue
<script setup>
import { ref, watch } from 'vue';
import Input from '@/components/new_form_elements/Input.vue';
import Textarea from '@/components/new_form_elements/Textarea.vue';
import Form from '@/components/new_form_builder/Form.vue';
import SelectPrivilegeInput from '../components/SelectPrivilegeInput.vue';

const props = defineProps({
  roles: {
    type: Object,
  },
  privileges: {
    type: Array,
    required: true,
  },
  selectedPrivilege: {
    type: Array,
    default: () => [],
  },
});

const selectedPrivileges = ref(props.selectedPrivilege);

watch(
  () => props.selectedPrivilege,
  (newVal) => {
    selectedPrivileges.value = newVal;
  },
  { immediate: true }
);
</script>

<template>
  <Form
    v-if="roles"
    class="grid grid-cols-3 gap-4 p-6"
    :inner="false"
    id="roleForm"
  >
    <Input
      name="roleName"
      validation="required"
      label="Role Name"
      :modelValue="roles.roleName"
      :attributes="{
        placeholder: 'Enter Role Name',
      }"
    />

    <Textarea
      name="roleDescription"
      validation="required"
      label="Role Description"
      :modelValue="roles.roleDescription"
      :attributes="{
        placeholder: 'Enter Role Description',
      }"
    />

    <div class="col-span-3">
      <SelectPrivilegeInput
        label="Select Privileges"
        validation="required"
        name="privilegeUuid"
        :options="privileges"
        :selectedPrivilege="selectedPrivileges"
      />
    </div>
  </Form>
</template>

<style scoped>
/* Form styling */
</style>
