// src/pages/admin/privileges/pages/EditPrivilege.jsx
import React, { useState, useEffect } from 'react';
import { useParams, useNavigate } from 'react-router-dom';
import { getPrivilegeById, updatePrivilege } from '@/pages/admin/api/AdminApi';
import { useApiRequest } from '@/composables/useApiRequest';
import { toasted } from '@/utils/toast';
import PrivilegeForm from '../component/PrivilegeForm';
import Button from '@/components/Button';

const EditPrivilege = () => {
  const { privilegeUuid } = useParams();
  const navigate = useNavigate();
  const [privilege, setPrivilege] = useState({});
  const [formData, setFormData] = useState({
    privilegeName: '',
    privilegeDescription: '',
    privilegeCategory: '',
  });
  const req = useApiRequest();
  const updateReq = useApiRequest();

  useEffect(() => {
    if (privilegeUuid && !Object.keys(privilege).length) {
      req.send(
        () => getPrivilegeById(privilegeUuid),
        (res) => {
          if (res.success) {
            setPrivilege(res.data);
            setFormData({
              privilegeName: res.data?.privilegeName || '',
              privilegeDescription: res.data?.privilegeDescription || '',
              privilegeCategory: res.data?.privilegeCategory || '',
            });
          }
        }
      );
    }
  }, [privilegeUuid]);

  const handleFormChange = (data) => {
    setFormData(data);
  };

  const handleUpdate = (e) => {
    e.preventDefault();
    updateReq.send(
      () => updatePrivilege(privilegeUuid, formData),
      (res) => {
        if (res.success) {
          setPrivilege((prev) => ({ ...prev, ...formData }));
          toasted(true, 'Successfully Updated', 'Privilege has been updated');
          setTimeout(() => {
            navigate(-1);
          }, 1500);
        } else {
          toasted(false, 'Error', res.error || 'Failed to update privilege');
        }
      }
    );
  };

  const handleGoBack = () => {
    navigate(-1);
  };

  return (
    <div className="min-h-screen bg-gradient-to-br from-gray-50 to-gray-100 p-4 sm:p-6 lg:p-8">
      <div className="max-w-7xl mx-auto">
        <button
          onClick={handleGoBack}
          className="inline-flex items-center gap-2 px-4 py-2 mb-6 text-gray-700 hover:text-gray-900 hover:bg-white rounded-lg transition-all duration-200 shadow-sm hover:shadow-md"
        >
          <svg
            width="7"
            height="13"
            viewBox="0 0 7 13"
            fill="none"
            xmlns="http://www.w3.org/2000/svg"
            className="w-5 h-5"
          >
            <path
              opacity="0.6"
              fillRule="evenodd"
              clipRule="evenodd"
              d="M5.82539 1.0134C6.03505 1.20471 6.05933 1.54072 5.87962 1.76391L2.15854 6.38525L5.87962 11.0066C6.05933 11.2298 6.03505 11.5658 5.82539 11.7571C5.61572 11.9484 5.30007 11.9226 5.12036 11.6994L1.12037 6.73164C0.959876 6.53232 0.959876 6.23819 1.12037 6.03887L5.12036 1.07113C5.30008 0.847943 5.61572 0.822096 5.82539 1.0134Z"
              fill="currentColor"
              stroke="currentColor"
              strokeLinecap="round"
            />
          </svg>
          <span className="font-medium">Go Back</span>
        </button>

        <div className="bg-white rounded-2xl shadow-xl overflow-hidden">
          <div className="bg-gradient-to-r from-indigo-600 to-indigo-700 px-6 sm:px-8 py-8">
            <h1 className="text-3xl sm:text-4xl font-bold text-white">Update Privilege</h1>
            <p className="text-indigo-100 mt-2">Manage privilege details and settings</p>
          </div>

          <div className="p-6 sm:p-8">
            {req.pending ? (
              <div className="flex flex-col items-center justify-center py-16">
                <div className="relative w-12 h-12 mb-4">
                  <div className="absolute inset-0 bg-indigo-200 rounded-full animate-pulse"></div>
                  <div className="absolute inset-0 flex items-center justify-center">
                    <div className="w-8 h-8 bg-indigo-600 rounded-full animate-spin"></div>
                  </div>
                </div>
                <p className="text-gray-600 font-medium">Loading privilege...</p>
              </div>
            ) : (
              <form onSubmit={handleUpdate}>
                <PrivilegeForm
                  privilege={privilege}
                  formData={formData}
                  onFormChange={handleFormChange}
                />

                <div className="mt-8 flex justify-end gap-3 pt-6 border-t border-gray-200">
                  <Button
                    variant="secondary"
                    size="md"
                    type="button"
                    onClick={handleGoBack}
                  >
                    Cancel
                  </Button>
                  <Button
                    variant="primary"
                    size="md"
                    type="submit"
                    loading={updateReq.pending}
                  >
                    {updateReq.pending ? 'Updating...' : 'Update Privilege'}
                  </Button>
                </div>
              </form>
            )}
          </div>
        </div>
      </div>
    </div>
  );
};

export default EditPrivilege;

// src/features/admin/privilege/pages/EditPrivilege.vue
<script setup>
import { useRoute, useRouter } from 'vue-router';
import { useApiRequest } from '@/composables/useApiRequest';
import { getPrivilegeById, updatePrivilege } from '../Api/PrivilegeApi';
import PrivilegeForm from '../form/PrivilegeForm.vue';
import { usePrivilege } from '../store/privilegeStore';
import { ref, watch } from 'vue';
import { toasted } from '@/utils/utils.js';
import Button from '@/components/Button.vue';
import { useForm } from '@/components/new_form_builder/useForm';

const router = useRouter();
const { submit } = useForm('privilegeForm');
const privilegeStore = usePrivilege();
const route = useRoute();
const privilegeUuid = route.params.privilegeUuid;
const req = useApiRequest();
const updateReq = useApiRequest();


const privilege = ref(
    privilegeStore.privilege.find((el) => el.privilegeUuid == privilegeUuid) || {}
);

if (!Object.keys(privilege.value).length) {
    req.send(
        () => getPrivilegeById(privilegeUuid),
        (res) => {
            if (res.success) {
                privilege.value = res.data;
               
            }
        }
    );
} 


function update({ values }) {
     updateReq.send(
        () => updatePrivilege(privilegeUuid, values),
        (res) => {
            if (res.success) {
                privilegeStore.update(privilegeUuid, { ...privilege.value, ...values });
                router.push('/privileges');
                toasted(res.success, 'Successfully Updated', res.error);
            } else {
                toasted(false, '', res.error || 'Failed to update privilege');
            }
        }
    );
}


</script>
<template>
  
   <div class=" bg-white p-4 rounded-xl space-y-6">
  <h1 class=" border-b font-semibold p-4">Update privilege</h1>
        <PrivilegeForm 
            :privilege="privilege" 
            
        />
        
        <div class="mt-4 px-4 py-3 bg-yellow-50 border border-yellow-200 rounded-md">
            <p class="text-sm text-yellow-700">
                <strong>Note:</strong> All fields must be at least 3 characters long. Privilege Name and Category must be less than 50 characters.
            </p>
        </div>
   
        <Button 
            size="md" 
           
            class="flex justify-center w-full items-center mt-3 gap-3 p-4  text-white bg-primary"
            :pending="updateReq.pending.value" 
            @click.prevent="submit(update)"
        >
            Update Privilege
        </Button>
   </div>
</template>
