// src/features/admin/role/components/SelectPrivilegeInput.vue
<script setup>
import InputParent from '@/components/new_form_builder/InputParent.vue';
import InputError from '@/components/new_form_elements/InputError.vue';
import { computed, ref, watch } from 'vue';

const props = defineProps({
  label: String,
  value: String,
  options: {
    type: Array,
    required: true,
  },
  selectedPrivilege: {
    type: Array,
  },
  validation: String,
  name: String,
});

const selected = ref([]);

const group = computed(() => {
  return props?.options.reduce((state, el) => {
    const category = el.privilegeCategory || 'Other';
    if (state[category]) {
      state[category].push(el);
    } else {
      state[category] = [el];
    }
    return state;
  }, {});
});

const totalCount = computed(() => props.options?.length || 0);
const selectedCount = computed(() => selected.value.length);

function categoryClasses(category) {
  const map = {
    user: 'from-sky-500 to-blue-600 border-blue-300',
    student: 'from-emerald-500 to-teal-600 border-emerald-300',
    university: 'from-amber-500 to-orange-600 border-amber-300',
    contract: 'from-fuchsia-500 to-pink-600 border-pink-300',
    program: 'from-indigo-500 to-blue-600 border-indigo-300',
    document: 'from-cyan-500 to-sky-600 border-cyan-300',
    privilege: 'from-purple-500 to-violet-600 border-violet-300',
    role: 'from-rose-500 to-red-600 border-rose-300',
    services: 'from-teal-500 to-emerald-600 border-teal-300',
    'credit invoice': 'from-orange-500 to-amber-600 border-orange-300',
  };
  return map[(category || '').toLowerCase()] || 'from-slate-400 to-slate-600 border-slate-300';
}

function categoryTextClass(category) {
  const map = {
    user: 'text-blue-700',
    student: 'text-emerald-700',
    university: 'text-orange-700',
    contract: 'text-pink-700',
    program: 'text-indigo-700',
    document: 'text-cyan-700',
    privilege: 'text-violet-700',
    role: 'text-rose-700',
    services: 'text-teal-700',
    'credit invoice': 'text-orange-700',
  };
  return map[(category || '').toLowerCase()] || 'text-slate-700';
}

function categoryBorderClass(category) {
  const map = {
    user: 'border-l-4 border-blue-400',
    student: 'border-l-4 border-emerald-400',
    university: 'border-l-4 border-amber-400',
    contract: 'border-l-4 border-pink-400',
    program: 'border-l-4 border-indigo-400',
    document: 'border-l-4 border-cyan-400',
    privilege: 'border-l-4 border-violet-400',
    role: 'border-l-4 border-rose-400',
    services: 'border-l-4 border-teal-400',
    'credit invoice': 'border-l-4 border-orange-400',
  };
  return map[(category || '').toLowerCase()] || 'border-l-4 border-slate-300';
}

watch(
  () => props.selectedPrivilege,
  (newPrivileges) => {
    if (!Array.isArray(newPrivileges)) {
      selected.value = [];
      return;
    }
    selected.value = [];
    newPrivileges.forEach((el) => {
      if (typeof el === 'string') {
        selected.value.push(el);
      } else if (el && el.privilegeUuid) {
        selected.value.push(el.privilegeUuid);
      }
    });
  },
  { immediate: true, deep: true }
);

function toggle(id) {
  if (!selected.value.includes(id)) {
    selected.value.push(id);
  } else {
    const idx = selected.value.findIndex((el) => el == id);
    idx > -1 && selected.value.splice(idx, 1);
  }
}

const isChecked = computed(() => {
  return (id) => selected.value.includes(id);
});

const isAllChecked = computed(() => {
  return (category) =>
    group.value[category].every((el) =>
      selected.value.includes(el.privilegeUuid)
    );
});

function selectAll(checked, category) {
  const ids = group.value[category].map((el) => el.privilegeUuid);
  selected.value = selected.value.filter((el) => !ids.includes(el));
  if (checked) {
    selected.value = [...selected.value, ...ids];
  }
}
</script>

<template>
  <InputParent
    :validation="validation"
    :name="name"
    v-model="selected"
    v-slot="{ setRef, error }"
  >
    <div :ref="setRef" class="flex flex-col gap-3">
      <!-- Header with badges -->
      <div class="flex items-center justify-between gap-2 border-b py-2">
        <div class="flex items-center gap-3">
          <span
            :data-required="`${validation}`.includes('required') ? 'true' : 'false'"
            :title="label"
            class="text-sm capitalize px-1 truncate"
            v-if="label"
          >{{ label }}</span>
          <InputError :error="error" />
        </div>

        <div class="flex items-center gap-2">
          <!-- Total badge with hover breakdown by category -->
          <div class="relative group">
            <span class="inline-flex items-center gap-1 rounded-full border px-3 py-1 text-xs font-semibold bg-white text-slate-700">
              Total: {{ totalCount }}
            </span>
            <div class="absolute z-20 hidden group-hover:block right-0 mt-2 w-64 bg-white border border-gray-200 rounded-lg shadow-lg p-3 text-left">
              <div class="text-xs font-semibold text-gray-700 mb-2">By Category</div>
              <ul class="max-h-60 overflow-auto space-y-1">
                <li v-for="cat in Object.keys(group)" :key="cat" class="flex items-center justify-between text-xs">
                  <span class="truncate">{{ cat }}</span>
                  <span class="text-gray-600">{{ group[cat].length }}</span>
                </li>
              </ul>
            </div>
          </div>

          <!-- Selected badge -->
          <span class="inline-flex items-center gap-1 rounded-full border px-3 py-1 text-xs font-semibold bg-blue-50 text-blue-700 border-blue-200">
            Selected: {{ selectedCount }}
          </span>
        </div>
      </div>

      <!-- Category sections -->
      <div class="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 xl:grid-cols-4 gap-4">
        <div v-for="category in Object.keys(group)" :key="category" :class="`rounded-xl border border-white/70 shadow-sm bg-white/80 backdrop-blur ${categoryBorderClass(category)}`">
          <div class="flex items-center justify-between px-3 py-2 border-b">
            <div class="flex items-center gap-2">
              <input
                :checked="isAllChecked(category)"
                @click="(ev) => selectAll(ev.target.checked, category)"
                class="h-4 w-4 rounded border-gray-300 text-blue-600 focus:ring-blue-500"
                type="checkbox"
                :aria-label="`Select all in ${category}`"
              />
              <p class="font-semibold text-sm capitalize" :class="categoryTextClass(category)">{{ category }}</p>
            </div>
            <span :class="`inline-flex items-center text-[10px] font-semibold text-white rounded-full px-2 py-0.5 border bg-gradient-to-r ${categoryClasses(category)}`">
              {{ group[category].length }}
            </span>
          </div>

          <div class="p-3 space-y-2 max-h-56 overflow-auto">
            <label
              v-for="privilege in group[category]"
              :key="privilege.privilegeUuid"
              class="flex items-center gap-2 text-sm cursor-pointer hover:bg-gray-50 rounded px-1 py-0.5"
            >
              <input
                :checked="isChecked(privilege.privilegeUuid)"
                @click="toggle(privilege.privilegeUuid)"
                class="h-4 w-4 rounded border-gray-300 text-blue-600 focus:ring-blue-500"
                type="checkbox"
                :aria-label="`Select ${privilege.privilegeName}`"
              />
              <span class="text-xs truncate" :title="privilege.privilegeName">{{ privilege.privilegeName }}</span>
            </label>
          </div>
        </div>
      </div>
    </div>
  </InputParent>
</template>

// src/pages/admin/roles/component/SelectPrivilegeInput.jsx
import React, { useMemo } from 'react';

const SelectPrivilegeInput = ({
  label,
  name,
  options = [],
  selectedPrivileges = [],
  onChange,
  required = false,
}) => {
  const groupedPrivileges = useMemo(() => {
    return options.reduce((acc, privilege) => {
      const category = privilege.privilegeCategory || 'Uncategorized';
      if (!acc[category]) {
        acc[category] = [];
      }
      acc[category].push(privilege);
      return acc;
    }, {});
  }, [options]);

  const getSelectedPrivilegeUuids = () => {
    if (!Array.isArray(selectedPrivileges)) return [];
    return selectedPrivileges.map((priv) => {
      if (typeof priv === 'string') return priv;
      return priv.privilegeUuid || priv.id;
    });
  };

  const selectedUuids = getSelectedPrivilegeUuids();

  const handleTogglePrivilege = (privilegeUuid) => {
    const updated = selectedUuids.includes(privilegeUuid)
      ? selectedUuids.filter((id) => id !== privilegeUuid)
      : [...selectedUuids, privilegeUuid];
    onChange(updated);
  };

  const isChecked = (privilegeUuid) => {
    return selectedUuids.includes(privilegeUuid);
  };

  const isAllCheckedInCategory = (category) => {
    const categoryPrivileges = groupedPrivileges[category] || [];
    return (
      categoryPrivileges.length > 0 &&
      categoryPrivileges.every((priv) =>
        selectedUuids.includes(priv.privilegeUuid)
      )
    );
  };

  const handleSelectAllInCategory = (category, checked) => {
    const categoryPrivileges = groupedPrivileges[category] || [];
    const categoryUuids = categoryPrivileges.map((priv) => priv.privilegeUuid);

    let updated;
    if (checked) {
      updated = [...new Set([...selectedUuids, ...categoryUuids])];
    } else {
      updated = selectedUuids.filter((id) => !categoryUuids.includes(id));
    }
    onChange(updated);
  };

  const categoryOrder = [
    'user',
    'role',
    'privilege',
    'post',
    'comment',
    'message',
    'institution',
    'like',
    'security',
  ];

  const sortedCategories = Object.keys(groupedPrivileges).sort((a, b) => {
    const aIndex = categoryOrder.indexOf(a);
    const bIndex = categoryOrder.indexOf(b);
    return (aIndex === -1 ? 999 : aIndex) - (bIndex === -1 ? 999 : bIndex);
  });

  const getCategoryColor = (category) => {
    const colors = {
      user: 'bg-blue-50 border-blue-200',
      role: 'bg-purple-50 border-purple-200',
      privilege: 'bg-indigo-50 border-indigo-200',
      post: 'bg-green-50 border-green-200',
      comment: 'bg-yellow-50 border-yellow-200',
      message: 'bg-pink-50 border-pink-200',
      institution: 'bg-cyan-50 border-cyan-200',
      like: 'bg-red-50 border-red-200',
      security: 'bg-orange-50 border-orange-200',
    };
    return colors[category] || 'bg-gray-50 border-gray-200';
  };

  const getCategoryBadgeColor = (category) => {
    const colors = {
      user: 'bg-blue-100 text-blue-800',
      role: 'bg-purple-100 text-purple-800',
      privilege: 'bg-indigo-100 text-indigo-800',
      post: 'bg-green-100 text-green-800',
      comment: 'bg-yellow-100 text-yellow-800',
      message: 'bg-pink-100 text-pink-800',
      institution: 'bg-cyan-100 text-cyan-800',
      like: 'bg-red-100 text-red-800',
      security: 'bg-orange-100 text-orange-800',
    };
    return colors[category] || 'bg-gray-100 text-gray-800';
  };

  return (
    <div className="w-full">
      <div className="flex items-center justify-between gap-2 mb-6 pb-3 border-b-2 border-gray-200">
        {label && (
          <span className="text-base font-bold text-gray-800">
            {label}
            {required && <span className="text-red-500 ml-2">*</span>}
          </span>
        )}
        {selectedUuids.length > 0 && (
          <span className="text-sm font-medium text-blue-600 bg-blue-50 px-3 py-1 rounded-full">
            {selectedUuids.length} selected
          </span>
        )}
      </div>

      <div className="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-4 gap-4">
        {sortedCategories.map((category) => (
          <div
            key={category}
            className={`border-2 rounded-lg p-4 transition-all duration-200 hover:shadow-md ${getCategoryColor(
              category
            )}`}
          >
            <div className="flex items-center gap-3 mb-4 pb-3 border-b-2 border-current border-opacity-20">
              <input
                type="checkbox"
                id={`select-all-${category}`}
                className="w-5 h-5 accent-blue-600 rounded cursor-pointer transition-all"
                checked={isAllCheckedInCategory(category)}
                onChange={(e) =>
                  handleSelectAllInCategory(category, e.target.checked)
                }
              />
              <label
                htmlFor={`select-all-${category}`}
                className="font-semibold text-sm text-gray-800 cursor-pointer flex-1 capitalize"
              >
                {category}
              </label>
              <span
                className={`text-xs font-bold px-2 py-1 rounded-full ${getCategoryBadgeColor(
                  category
                )}`}
              >
                {groupedPrivileges[category]?.length || 0}
              </span>
            </div>

            <div className="space-y-2">
              {(groupedPrivileges[category] || []).map((privilege) => (
                <div
                  key={privilege.privilegeUuid}
                  className="flex items-start gap-3 p-2 rounded hover:bg-white hover:bg-opacity-50 transition-colors"
                >
                  <input
                    type="checkbox"
                    id={`priv-${privilege.privilegeUuid}`}
                    className="w-4 h-4 accent-blue-600 rounded cursor-pointer mt-0.5 transition-all"
                    checked={isChecked(privilege.privilegeUuid)}
                    onChange={() =>
                      handleTogglePrivilege(privilege.privilegeUuid)
                    }
                  />
                  <label
                    htmlFor={`priv-${privilege.privilegeUuid}`}
                    className="flex-1 cursor-pointer"
                  >
                    <p className="text-sm font-medium text-gray-800 leading-tight">
                      {privilege.privilegeName}
                    </p>
                    <p className="text-xs text-gray-600 mt-0.5">
                      {privilege.privilegeDescription}
                    </p>
                  </label>
                </div>
              ))}
            </div>
          </div>
        ))}
      </div>

      {Object.keys(groupedPrivileges).length === 0 && (
        <div className="text-center py-12">
          <svg
            className="w-12 h-12 mx-auto text-gray-300 mb-3"
            fill="none"
            stroke="currentColor"
            viewBox="0 0 24 24"
          >
            <path
              strokeLinecap="round"
              strokeLinejoin="round"
              strokeWidth={1.5}
              d="M9 12l2 2 4-4m6 2a9 9 0 11-18 0 9 9 0 0118 0z"
            />
          </svg>
          <p className="text-gray-500 font-medium">No privileges available</p>
        </div>
      )}
    </div>
  );
};

export default SelectPrivilegeInput;
