// src/features/admin/privilege/form/PrivilegeForm.vue
<script setup>
import Form from "@/components/new_form_builder/Form.vue";
import Input from "@/components/new_form_elements/Input.vue";
import Select from "@/components/new_form_elements/Select.vue";
import { ref, watch, onMounted } from "vue";
import vPrivilege from "@/directives/vPrivilage";

const props = defineProps({
  privilege: {
    type: Object,
    default: () => ({}),
  },
});

const privilegeType = ref([
  {
    label: "For All",
    value: "FOR_ALL",
  },
  {
    label: "Admin",
    value: "FOR_SYSTEM_ADMIN",
  },
  {
    label: "Provider",
    value: "FOR_PROVIDER",
  },
  {
    label: "Payer",
    value: "FOR_PAYER",
  },
]);
</script>
<template>
  <Form
    class="grid grid-cols-2 gap-x-20 gap-y-4"
    :inner="false"
    id="privilegeForm"
  >
    <Input
      name="privilegeName"
      validation="required|minmax-3,50 (Minimum length is 3 characters.)"
      label="Privilege Name"
      :value="props.privilege?.privilegeName || ''"
      :attributes="{
        placeholder: 'Enter Privilege',
      }"
    />
    <Input
      validation="required|minmax-3,50 (Minimum length is 3 characters.)"
      name="privilegeDescription"
      :value="props.privilege?.privilegeDescription || ''"
      label="Privilege Description"
      :attributes="{
        placeholder: 'Enter Privilege description',
      }"
    />
    <Input
      :value="props.privilege?.privilegeCategory || ''"
      name="privilegeCategory"
      label="Privilege Category"
      validation="required|minmax-3,50 (Minimum length is 3 characters.)"
      :attributes="{
        placeholder: 'Enter Privilege Category',
      }"
    />
    <Select
      :obj="true"
      :value="props.privilege?.privilegeType"
      name="privilegeType"
      validation="required"
      label="Privilege Type"
      :options="privilegeType"
      :attributes="{
        placeholder: 'Select Privilege Type',
      }"
    />
  </Form>
</template>

// src/pages/admin/privileges/component/PrivilegeForm.jsx
import React, { useEffect, useState } from 'react';
import Input from '@/components/Input';

const PrivilegeForm = ({ 
  privilege = {}, 
  formData = {},
  onFormChange 
}) => {
  const [form, setForm] = useState({
    privilegeName: privilege?.privilegeName || '',
    privilegeDescription: privilege?.privilegeDescription || '',
    privilegeCategory: privilege?.privilegeCategory || '',
  });

  useEffect(() => {
    if (privilege?.privilegeUuid) {
      setForm({
        privilegeName: privilege?.privilegeName || '',
        privilegeDescription: privilege?.privilegeDescription || '',
        privilegeCategory: privilege?.privilegeCategory || '',
      });
    }
  }, [privilege?.privilegeUuid]);

  const handleInputChange = (e) => {
    const { name, value } = e.target;
    const updated = {
      ...form,
      [name]: value,
    };
    setForm(updated);
    if (onFormChange) {
      onFormChange(updated);
    }
  };

  return (
    <div className="space-y-6">
      <div className="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-4 gap-6">
        <div className="bg-gray-50 rounded-lg p-6 border border-gray-200">
          <Input
            name="privilegeName"
            label="Privilege Name"
            value={form.privilegeName}
            onChange={handleInputChange}
            placeholder="e.g., create_user, delete_post"
            required
          />
        </div>

        <div className="sm:col-span-2 bg-gray-50 rounded-lg p-6 border border-gray-200">
          <Input
            name="privilegeDescription"
            label="Privilege Description"
            value={form.privilegeDescription}
            onChange={handleInputChange}
            placeholder="Describe what this privilege allows"
            required
          />
        </div>

        <div className="bg-gray-50 rounded-lg p-6 border border-gray-200">
          <Input
            name="privilegeCategory"
            label="Privilege Category"
            value={form.privilegeCategory}
            onChange={handleInputChange}
            placeholder="e.g., user, post, role"
            required
          />
        </div>
      </div>
    </div>
  );
};

export default PrivilegeForm;
